### ISSUE TITLE
[BUG] Crashes when playing premier game

### ISSUE THREAD

**Issue by ICEDStriker** [Retr0-01/CSGO-Discord-RP#4]
**Describe the bug**
the app works when im in then main menu and shows it on discord, but as soon as i load in an ranked match (premier, i havent tried it on normal ranked matches) the app crashes

**To Reproduce**
1. open CS2
2. join premier match

**Expected behavior**
doesnt crash

**Desktop (please complete the following information):**
- OS: windows
- Version 2.0.0

**Comment by ICEDStriker** [comment]
well now i found out it crashes every time i go in a match it doesnt matter if its premier/casual/ranked

**Comment by Retr0-01** [comment]
Hello,

I apologize for the delay. I will have any issues related to this app fixed by the end of the next week. I am on a pretty tight schedule right now so I cannot look at it immediately.

Thanks.
