### ISSUE TITLE
[BUG] Error while trying to open

### ISSUE THREAD

**Issue by Meff1u** [Retr0-01/CSGO-Discord-RP#5]
**Describe the bug**
After trying to run the .exe file, nothing happens, so I checked the event log and it shows this error:

**To Reproduce**
1. Run .exe file (while discord and cs2 are running)

**Expected behavior**
Working RPC

**Screenshots**
![image](https://github.com/Retr0-01/CS2-Discord-RP/assets/42370647/2d8d8331-e371-4e0c-b4c5-c59599bc919f)

**Desktop (please complete the following information):**
- OS: Windows 11 23H2 (22635.2419)
- Version: 2.0.0
- Game Version: Latest on 15.10.2023

**Additional context**
Translation for screenshot:
Name of the application causing the error: CS2-Discord-RP.exe, version: 1.0.0.0, time signature: 0x64e81091
Name of the module causing the error: KERNELBASE.dll, version: 10.0.22621.2419, time signature: 0xa85ef443
Exception code: 0xe0434352
Error offset: 0x001490e2
ID of the process causing the error: 0x0x5558
Start time of the application causing the error: 0x0x1D9FF7062809493
Path of the application causing the error: E:Program Files\CS2-Discord-RP\CS2-Discord-RP.exe.
Path of the module causing the error: C:WINDOWSystem32KERNELBASE.dll.
Report ID: 0b12c465-1860-4b95-b217-47bfa69f2b58
Full name of the package causing the error: 
Application ID relative to the package causing the error:

**Comment by Meff1u** [comment]
Also there is an error with .NET Runtime source:
```Application: CS2-Discord-RP.exe
CoreCLR Version: 6.0.2223.42425
.NET Version: 6.0.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.HttpListenerException (183): Failed to listen on prefix 'http://localhost:3000/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at RichPresenceApp.HttpServer.Start()
   at RichPresenceApp.RichPresenceAppContext..ctor()
   at RichPresenceApp.Program.Main()```

**Comment by Meff1u** [comment]
if i change localhost port in .cfg file error is still the same cus app overwrites it to 3000

**Comment by Meff1u** [comment]
There are also HttpService logs with CreateUrlGroup, AddUrl, RemUrl and DeleteUrlGroup operation codes

**Comment by Retr0-01** [comment]
Hello,

I apologize for the delay. I will have any issues related to this app fixed by the end of the next week. I am on a pretty tight schedule right now so I cannot look at it immediately.

Thanks.

**Comment by Meff1u** [comment]
No worries, thanks for respond :)

**Comment by Retr0-01** [comment]
This should be fixed at the [latest release](https://github.com/Retr0-01/CS2-Discord-RP/releases/latest) of the app.

I went ahead and changed the port to a less-used one. Also, there will be an error shown to you in case the same or a similar exception occur. Feel free to re-open the issue if it still persists.
