### ISSUE TITLE
[BUG] Rich Presence crashes when getting into a match.

### ISSUE THREAD

**Issue by CorsoMaxima** [Retr0-01/CSGO-Discord-RP#6]
Hello, so I have been using the program for a while now, but whenever I get into a match, it crashes.

To reproduce:
1. Open the game, alongside with the rich presence
2. Just queue for any mode, or get into practice
3. And it crashes

- OS: Windows 10
- Version: latest
- Game Version: latest CS2

**Comment by Retr0-01** [comment]
Hello. Can you try opening the console and while joining a match see what it prints? The app runs fine on my end so I need some extra details.

**Comment by CorsoMaxima** [comment]
> Hello. Can you try opening the console and while joining a match see what it prints? The app runs fine on my end so I need some extra details.

I'm on it.

**Comment by CorsoMaxima** [comment]
[log.txt](https://github.com/Retr0-01/CS2-Discord-RP/files/13213924/log.txt)

**Comment by Retr0-01** [comment]
Sorry but I meant the app console not the game console... 😅
If you right click on the tray icon of the app you will see a button which will show the console.

![image](https://github.com/Retr0-01/CS2-Discord-RP/assets/61121754/377b3118-6f12-4e11-bbe0-18144fbb0532)

**Comment by CorsoMaxima** [comment]
My bad.
![image](https://github.com/Retr0-01/CS2-Discord-RP/assets/80535998/68da92e9-e353-4f9f-884e-14b3ba670d4c)

**Comment by Retr0-01** [comment]
Can you tell me the path of your CS2 installation. You can do that by going to your Steam library, right click on CS2 -> Manage -> Browse local files.

**Comment by CorsoMaxima** [comment]
> Can you tell me the path of your CS2 installation. You can do that by going to your Steam library, right click on CS2 -> Manage -> Browse local files.

C:\HammerAutosave\steamapps\common\Counter-Strike Global Offensive\

**Comment by CorsoMaxima** [comment]
Hello! Anything new?

**Comment by Retr0-01** [comment]
Hello and sorry for the late reply.

I am not sure as to what is causing this since it works just fine on my end and another machine I used to test it but I will look into it further. I will keep this issue open for now.
