### ISSUE TITLE
[BUG] RPC isn't visible but active

### ISSUE THREAD

**Issue by Meff1u** [Retr0-01/CSGO-Discord-RP#7]
**Describe the bug**
Tried in match, lobby, etc, nothing works

**To Reproduce**
1. Join game/match

**Expected behavior**
Visible RPC in discord profile

**Screenshots**
https://i.imgur.com/FmitDCz.png
https://i.imgur.com/PJ1dJok.png

**Desktop (please complete the following information):**
- OS: Windows 11
- Version 10.0.22635.2700
- Game Version: latest (17.11.2023)

**Additional context**
no errors in audit log

**Comment by Meff1u** [comment]
theres also nothing showing up in cs2 rpc console 
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/42370647/283949013-1a60166e-da8e-4724-ad81-c9350f623083.png)

**Comment by Retr0-01** [comment]
Hello have you tried the following:
- Ensure that you have Activity Presence enabled on Discord.
- Ensure that CS2 is recognized on your Discord games.

**Comment by Meff1u** [comment]
1. Im sure that activity presence is enabled, cus i am using premid for yt or sth and it works fine
2. i think it recognizes, it shows cs2 but not as rich presence (second screenshot)

**Comment by Meff1u** [comment]
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/42370647/283960489-e9a8645b-7ebc-4e45-aaa7-38c5f112c195.png)
as an example that activity presence is enabled

**Comment by Retr0-01** [comment]
Hello and sorry for the late reply.

I am not sure as to what is causing this since it works just fine on my end and another machine I used to test it but I will look into it further. I will keep this issue open for now.
