### ISSUE TITLE
[BUG] The RPC is not working

### ISSUE THREAD

**Issue by adabugra** [Retr0-01/CSGO-Discord-RP#8]
**Describe the bug**
I am opening the exe but the RPC ony shows normal cs2 rpc.

**Desktop (please complete the following information):**
- Windows 11
- Vencord installed on discord

![image](https://github.com/Retr0-01/CS2-Discord-RP/assets/57899270/4177159b-9517-456d-8f00-690e1bc4383f)

**Comment by Retr0-01** [comment]
Hello and sorry for the late reply.

I am not sure as to what is causing this since it works just fine on my end and another machine I used to test it but I will look into it further. I will keep this issue open for now.
